name: Deploy Schema

on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: college-app-366823
  REGION: asia-northeast1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    container: node:18
    environment: apollo
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"
      - run: npm ci
      - run: npm run generate:schema
        env: 
          JWT_SECRET_KEY: hoge
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.9.1 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - run: |
          rover subgraph publish college-app-supergraph@main --schema ./src/schema.gql --name college-app 
