name: Migrate

on:
  push:
    branches: [ "main" ]

jobs:
  migration:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Google Auth
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"
          token_format: "access_token"

      - run: docker pull gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0-preview.1

      - run: docker run -d gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0-preview.1 ./cloud-sql-proxy college-app-366823:asia-northeast1:college-app --token ${{ steps.auth.outputs.access_token }}

      - name: Cloud SQL migration
        run: npx prisma migrate deploy
        env: 
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL: postgresql://postgres:example@localhost:5432/postgres