name: Migrate

on:
  push:
    branches: [ "main" ]

jobs:
  login:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.auth.outputs.access_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"
          token_format: "access_token"

      - run: |
          echo "ACCESS_TOKEN=${{ steps.auth.outputs.access_token }}" >> $GITHUB_ENV
      
      - run: |
          echo ${{ env.ACCESS_TOKEN }}
  migration:
    needs: 'login'
    runs-on: ubuntu-latest
    container: node:18
    services:
      myservice1:
        image: ghcr.io/owner/myservice1
        credentials:
          username: oauth2accesstoken
          password: ${{ needs.login.outpus.access_token }}
      # proxy:
      #   image: gcr.io/college-app-366823/csap
      #   credentials:
      #     username: 'oauth2accesstoken'
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #   options: >-
      #     --health-cmd 'curl -f http://localhost:8090 || exit 1'
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cloud SQL migration
        run: npx prisma migrate deploy
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}