name: Migrate

on:
  push:
    branches: [ "main" ]

jobs:
  migration:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"
          token_format: "access_token"

      - run: |
          URL="https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.0.0-preview.2"

          wget "$URL/cloud-sql-proxy.linux.amd64" -O cloud-sql-proxy

          chmod +x cloud-sql-proxy

          ./cloud-sql-proxy college-app-366823:asia-northeast1:college-app --token ${{ steps.auth.outputs.access_token }}

      - name: Cloud SQL migration
        run: npx prisma migrate deploy
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}